version: '3.9'

services:

  mongodb-primary:
    image: bitnami/mongodb:latest
    hostname: data-lake
    deploy:
      mode: global
    ports:
      - '27017:27017'
    environment:
      MONGODB_DATABASE: 'data-lake'
      MONGODB_USERNAME: 'user'
      MONGODB_PASSWORD: 'password'
      MONGODB_ADVERTISED_HOSTNAME: 'mongodb-primary'
      MONGODB_ROOT_PASSWORD: 'password'
      MONGODB_REPLICA_SET_MODE: 'primary'
      MONGODB_REPLICA_SET_KEY: 'replicaset0'
    networks:
      data-lake-network:

  mongodb-secondary:
    image: bitnami/mongodb:latest
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 'mongodb-secondary'
      MONGODB_INITIAL_PRIMARY_HOST: 'mongodb-primary'
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: 'password'
      MONGODB_REPLICA_SET_MODE: 'secondary'
      MONGODB_REPLICA_SET_KEY: 'replicaset0'
    networks:
      data-lake-network:

  mongodb-arbiter:
    image: bitnami/mongodb:latest
    deploy:
      mode: global
    depends_on:
      - mongodb-primary
    environment:
      MONGODB_ADVERTISED_HOSTNAME: 'mongodb-arbiter'
      MONGODB_INITIAL_PRIMARY_HOST: 'mongodb-primary'
      MONGODB_INITIAL_PRIMARY_ROOT_PASSWORD: 'password'
      MONGODB_REPLICA_SET_MODE: 'arbiter'
      MONGODB_REPLICA_SET_KEY: 'replicaset0'
    networks:
      data-lake-network:

networks:
  data-lake-network:
    external: true
