version: '3.9'

services:

  data-lake:
    image: mongo:latest
    hostname: data-lake
    deploy:
      mode: global
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_DATABASE: 'data-lake'
      MONGO_INITDB_ROOT_USERNAME: 'root'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    networks:
      data-lake-network:
    volumes:
      - ../config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ../../mongodb-storage/data:/data/db

networks:
  data-lake-network:
    external: true
