version: '3'

services:

  search-engine-ui:
    image: search-engine-ui
    hostname: search-engine-ui
    ports:
      - '4200:4200'
    networks:
      - search-engine-ui-network
    deploy:
      mode: replicated
      replicas: 1

networks:
  search-engine-ui-network:
