version: '3.9'

services:

  web-details-provider-service:
    image: web-details-provider-service:latest
    hostname: web-details-provider-service
    deploy:
      mode: replicated
      replicas: 1
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      - search-engine-network
      - data-lake-network

  search-engine-service:
    image: search-engine-service:latest
    hostname: search-engine-service
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - web-details-provider-service
    ports:
      - '10001:10001'
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      - search-engine-network
      - data-lake-network

networks:
  search-engine-network:
    external: true
  data-lake-network:
    external: true
