version: '3.9'

services:

  domain-feeder:
    image: domain-feeder:latest
    hostname: domain-feeder
    deploy:
      mode: global
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      web-crawler-network:
      data-lake-network:
    volumes:
      - ../input/allowed_domains.txt:/input/allowed_domains.txt:ro
      - ../input/startup_domains.txt:/input/startup_domains.txt:ro

  url-frontier:
    image: url-frontier:latest
    hostname: url-frontier
    deploy:
      mode: global
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      web-crawler-network:
      data-lake-network:
    volumes:
      - ../input/allowed_domains.txt:/input/allowed_domains.txt:ro
      - ../input/startup_urls.txt:/input/startup_urls.txt:ro

  document-handler:
    image: document-handler:latest
    hostname: document-handler
    deploy:
      mode: global
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      web-crawler-network:
      data-lake-network:

  domain-explorer:
    image: domain-explorer:latest
    hostname: domain-explorer
    deploy:
      replicas: 1
    depends_on:
      - domain-feeder
      - url-frontier
      - document-handler
    environment:
      SPRING_PROFILES_ACTIVE: 'demo'
    networks:
      web-crawler-network:

networks:
  web-crawler-network:
  data-lake-network:
    external: true
